defaultProject: jit-training-dma
defaultLocation: EU
defaultDataset: dataform
defaultAssertionDataset: dataform_assertions
dataformCoreVersion: 3.0.0
vars:
    destination_dataset: "Maurizio_academy"
